name: Nightly artifact release

on:
  workflow_dispatch:
    inputs:
      parameter:
        description: branch

jobs:
  build:
    runs-on: ubuntu-latest  # You can choose a different runner if needed
    permissions: write-all

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: development
        fetch-depth: 0

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11

    - name: Build Shaded JAR
      run: mvn clean package

    - name: Create Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: nightly
        prerelease: false
        title: Nightly Build
        files: runelite-client/target/*.jar

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Build Artifacts
        path: runelite-client/target/*.jar
